name: develop
on:
  push:
    branches:
      - develop

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'

  build_container:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: go mod tidy
      - run: make test
      - run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
      - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/tezos-prometheus-exporter:${{ branch }} .
